from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

from promptbridge.utils import read_text, write_text


DEFAULT_MEMORY_FILES: dict[str, str] = {
    "user_profile.md": """# User Profile

- The user is a graduate student in a job-search phase.
- The user wants PromptBridge to be a production-valued agent project, not a tutorial-style demo.
- Preferred explanation language: Chinese.
- Technical terms should usually keep their English names with Chinese explanation when needed.
""",
    "project_promptbridge.md": """# Project PromptBridge

## Primary User Goal

Build PromptBridge as a resume-quality, context-first multilingual Agent Gateway.

## Current Product Direction

PromptBridge should help non-English users use strong web or API models more effectively through context engineering, selective translation, local retrieval, tool economy, structured memory compaction, and browser collaboration.

## Confirmed Decisions

- Context Kernel Manager is the core module.
- Retrieval should be exact/lexical-first, with vector search only as a later fallback.
- BrowserBridge should stay thin and human-in-the-loop.
- Dream compaction should produce MemoryPatch proposals rather than silently overwriting memory.
""",
    "glossary.yaml": """terms:
  - term: Context Kernel
    zh: 上下文内核
    note: Structured working set for the current model request.
  - term: Retrieval Router
    zh: 检索路由器
    note: Chooses exact, lexical, structural, semantic, or web retrieval paths.
  - term: Memory Ledger
    zh: 记忆账本
    note: Append-only event log for auditable memory.
  - term: MemoryPatch
    zh: 记忆补丁
    note: Reviewable patch proposal generated by DreamCompactor.
  - term: Tool Economy Layer
    zh: 工具经济层
    note: Keeps always-on tool definitions small and defers heavy tools.
  - term: BrowserBridge
    zh: 浏览器桥接
    note: Thin browser collaboration layer for capture, fill, overlay, and handoff.
  - term: MCP
    zh: Model Context Protocol
    note: External tool/server integration protocol; should be loaded with explicit tool economy constraints.
""",
    "failures.md": """# Failure Cases

- Avoid turning PromptBridge into a generic vector RAG demo.
- Avoid making BrowserBridge a full web automation/RPA system in v0.
- Avoid loading large tool schemas into every prompt.
""",
    "decisions.md": """# Project Decisions

- v0 is CLI-first.
- v0 uses Markdown/YAML memory files plus an append-only JSONL ledger.
- v0 compiles cache-aware execution prompts and records trace files for replay.
- Tool Economy Layer exists to control 工具成本 / tool-schema context cost by keeping always-on tools small and deferring heavy tools.
""",
    "open_threads.md": """# Open Threads

- Decide when to add a model-backed translation provider.
- Design BrowserBridge native host protocol after the CLI core stabilizes.
- Add eval replay and ablation metrics.
""",
}


@dataclass(frozen=True)
class GlossaryTerm:
    term: str
    zh: str
    note: str
    source_path: str


@dataclass
class MemoryWorkspace:
    root: Path

    @classmethod
    def from_path(cls, root: str | Path) -> "MemoryWorkspace":
        return cls(Path(root))

    @property
    def memory_dir(self) -> Path:
        return self.root / "memory"

    @property
    def ledger_dir(self) -> Path:
        return self.root / "ledger"

    @property
    def ledger_path(self) -> Path:
        return self.ledger_dir / "events.jsonl"

    @property
    def traces_dir(self) -> Path:
        return self.root / "traces"

    @property
    def patches_dir(self) -> Path:
        return self.root / "patches"

    @property
    def index_dir(self) -> Path:
        return self.root / "index"

    @property
    def compiled_dir(self) -> Path:
        return self.root / "compiled"

    @property
    def reconstructed_dir(self) -> Path:
        return self.root / "reconstructed"

    @property
    def outbox_dir(self) -> Path:
        return self.root / "outbox"

    def ensure_defaults(self) -> None:
        for directory in [
            self.memory_dir,
            self.ledger_dir,
            self.traces_dir,
            self.patches_dir,
            self.index_dir,
            self.compiled_dir,
            self.reconstructed_dir,
            self.outbox_dir,
        ]:
            directory.mkdir(parents=True, exist_ok=True)

        for name, content in DEFAULT_MEMORY_FILES.items():
            path = self.memory_dir / name
            if not path.exists():
                write_text(path, content)

        if not self.ledger_path.exists():
            write_text(self.ledger_path, "")

    def iter_memory_files(self) -> list[Path]:
        self.ensure_defaults()
        patterns = ["*.md", "*.yaml", "*.yml", "*.jsonl"]
        files: list[Path] = []
        for pattern in patterns:
            files.extend(self.memory_dir.glob(pattern))
        return sorted(path for path in files if path.is_file())

    def read_memory_files(self) -> dict[str, str]:
        return {str(path): read_text(path) for path in self.iter_memory_files()}

    def read_glossary_terms(self) -> list[GlossaryTerm]:
        glossary_path = self.memory_dir / "glossary.yaml"
        if not glossary_path.exists():
            return []

        terms: list[GlossaryTerm] = []
        current: dict[str, str] = {}

        for raw_line in read_text(glossary_path).splitlines():
            line = raw_line.rstrip()
            term_match = re.match(r"\s*-\s+term:\s*(.+)", line)
            field_match = re.match(r"\s+(zh|note):\s*(.+)", line)
            if term_match:
                if current.get("term"):
                    terms.append(_term_from_dict(current, glossary_path))
                current = {"term": _clean_yaml_value(term_match.group(1))}
            elif field_match and current:
                current[field_match.group(1)] = _clean_yaml_value(field_match.group(2))

        if current.get("term"):
            terms.append(_term_from_dict(current, glossary_path))
        return terms


def _clean_yaml_value(value: str) -> str:
    return value.strip().strip('"').strip("'")


def _term_from_dict(data: dict[str, str], path: Path) -> GlossaryTerm:
    return GlossaryTerm(
        term=data.get("term", ""),
        zh=data.get("zh", ""),
        note=data.get("note", ""),
        source_path=str(path),
    )
